In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#%matplotlib inline to plot inline
%matplotlib inline 
#? before plt.style.use to check what's available
plt.style.use('fivethirtyeight')
plt.rcParams['figure.figsize'] = (10, 6)

In [2]:
#2. import data set
df = pd.read_csv("../data/bank.csv")

In [5]:
#3. check column names
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [6]:
#import preprocessing library
#import scikit learn
from sklearn import preprocessing

In [7]:
df_encoded = df.apply(preprocessing.LabelEncoder().fit_transform)

In [8]:
df_encoded.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   41    0        1          1        0     2288        1     0        2   
1   38    0        1          1        0      469        0     0        2   
2   23    9        1          1        0     1618        1     0        2   
3   37    7        1          1        0     2356        1     0        2   
4   36    0        1          2        0      608        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    4      8      1021         0      0         0         3        1  
1    4      8      1283         0      0         0         3        1  
2    4      8      1246         0      0         0         3        1  
3    4      8       577         0      0         0         3        1  
4    4      8       671         1      0         0         3        1

In [9]:
#5. import linear regression
from sklearn.linear_model import LinearRegression

In [19]:
#loc is for label
df3 = df_encoded.loc[ 0:3 , "job" ]

In [23]:
#iloc is for integer loc
df3i = df_encoded.iloc[0:3, 2]

In [26]:
# this will create summary
df_encoded.describe()

age           job       marital     education       default  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      23.231410      4.487905      1.199337      1.285164      0.015051   
std       11.911048      3.225132      0.625552      0.749478      0.121761   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%       14.000000      1.000000      1.000000      1.000000      0.000000   
50%       21.000000      4.000000      1.000000      1.000000      0.000000   
75%       31.000000      7.000000      2.000000      2.000000      0.000000   
max       75.000000     11.000000      2.000000      3.000000      1.000000   

            balance       housing          loan       contact           day  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean    1327.318043      0.473123      0.130801      0.489697     14.658036   
std      965.056807      0.499299      0.337198      0.818724      8.420740   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%      546.000000      0.000000      0.000000      0.000000      7.000000   
50%      973.000000      0.000000      0.000000      0.000000     14.000000   
75%     1928.000000      1.000000      0.000000      1.000000     21.000000   
max     3804.000000      1.000000      1.000000      2.000000     30.000000   

              month      duration      campaign         pdays      previous  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean       5.445709    359.711521      1.503942     46.133668      0.824673   
std        3.191939    308.647769      2.652133     95.289292      2.156619   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        3.000000    136.000000      0.000000      0.000000      0.000000   
50%        6.000000    253.000000      1.000000      0.000000      0.000000   
75%        8.000000    494.000000      2.000000     14.750000      1.000000   
max       11.000000   1427.000000     35.000000    471.000000     33.000000   

           poutcome       deposit  
count  11162.000000  11162.000000  
mean       2.477782      0.473840  
std        1.002952      0.499338  
min        0.000000      0.000000  
25%        2.000000      0.000000  
50%        3.000000      0.000000  
75%        3.000000      1.000000  
max        3.000000      1.000000

In [38]:
X = df_encoded.iloc[:, :16]
y = df_encoded.iloc[:,  16]

In [39]:
#6. import accuracy_score 

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
#7. The first thing is to instantiate the linear regression
model_linear_reg = LinearRegression()

In [42]:
model_linear_reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [43]:
model_linear_reg.coef_

array([  8.45969478e-04,   1.53970191e-03,   3.05600591e-02,
         3.27894788e-02,  -2.83243422e-02,   3.68609035e-05,
        -1.73539180e-01,  -1.03748737e-01,  -1.01152801e-01,
        -1.56329178e-03,   7.26419995e-03,   7.69559977e-04,
        -1.33721042e-02,   6.12869169e-04,   2.02026938e-02,
         3.05241166e-02])

In [44]:
linear_reg_prediction = model_linear_reg.predict(X)

In [47]:
linear_reg_prediction

array([ 0.80695678,  1.11253279,  0.95404084, ...,  0.38342192,
        0.31670596,  0.77477897])

In [48]:
linear_reg_prediction_updated = linear_reg_prediction.copy()

In [49]:
#Set predictions above 0.5 as 1
linear_reg_prediction_updated[np.where(linear_reg_prediction_updated>0.5)] = 1
#Set predictions below 0.5 as 0
linear_reg_prediction_updated[np.where(linear_reg_prediction_updated<=0.5)] = 0

In [50]:
linear_reg_prediction_updated

array([ 1.,  1.,  1., ...,  0.,  0.,  1.])

In [53]:
accuracy_score(y, linear_reg_prediction_updated)

0.79376455832288118

# Running logistic regression

In [59]:
#import logistic regression
from sklearn.linear_model import LogisticRegression

In [56]:
model_all_logistic = LogisticRegression()

In [60]:
#max_iteration -> number of iteration
#tol -> tolerances
model_all_logistic

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [61]:
X.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   41    0        1          1        0     2288        1     0        2   
1   38    0        1          1        0      469        0     0        2   
2   23    9        1          1        0     1618        1     0        2   
3   37    7        1          1        0     2356        1     0        2   
4   36    0        1          2        0      608        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  
0    4      8      1021         0      0         0         3  
1    4      8      1283         0      0         0         3  
2    4      8      1246         0      0         0         3  
3    4      8       577         0      0         0         3  
4    4      8       671         1      0         0         3

In [62]:
model_all_logistic.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [63]:
pred_logistic = model_all_logistic.predict(X)

In [66]:
accuracy_score(y, pred_logistic)

0.79913993907901815

In [67]:
model_all_logistic.predict(X)

array([1, 1, 1, ..., 0, 0, 1])

In [65]:
model_all_logistic.predict_proba(X)

array([[ 0.09295494,  0.90704506],
       [ 0.01388682,  0.98611318],
       [ 0.03557652,  0.96442348],
       ..., 
       [ 0.6535073 ,  0.3464927 ],
       [ 0.77729603,  0.22270397],
       [ 0.11863213,  0.88136787]])

# Regularisation Process

In [68]:
model_all_logistic_L1 = LogisticRegression(penalty="l1")

In [69]:
model_all_logistic_L1.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [70]:
pred_logistic_l1 = model_all_logistic_L1.predict(X)

In [71]:
accuracy_score(y, pred_logistic_l1)

0.7989607597204802

In [72]:
model_all_logistic_L1.coef_

array([[  5.51801031e-03,   1.07345806e-02,   1.83700074e-01,
          2.06599270e-01,  -2.58544085e-01,   2.27710285e-04,
         -1.06156575e+00,  -6.86898403e-01,  -6.75085466e-01,
         -9.43773337e-03,   3.32497458e-02,   5.23404049e-03,
         -1.31276548e-01,   3.34568350e-03,   1.28174664e-01,
          1.70937117e-01]])

In [73]:
model_all_logistic.coef_

array([[  5.32737060e-03,   1.06419656e-02,   1.80470418e-01,
          2.03081618e-01,  -2.80831024e-01,   2.25881547e-04,
         -1.04546114e+00,  -7.01054657e-01,  -6.67058637e-01,
         -9.59113746e-03,   3.19117907e-02,   5.21432455e-03,
         -1.31586227e-01,   3.29229027e-03,   1.27794420e-01,
          1.65889265e-01]])

In [74]:
model_all_logistic_L1 = LogisticRegression(penalty="l1", C=0.001)

In [75]:
model_all_logistic_L1.fit(X, y)

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [76]:
pred_logistic_l1 = model_all_logistic_L1.predict(X)

In [77]:
accuracy_score(y, pred_logistic_l1)

0.73320193513707221

In [78]:
model_all_logistic_L1.coef_

array([[-0.01652733,  0.        ,  0.        ,  0.        ,  0.        ,
         0.00012862,  0.        ,  0.        ,  0.        , -0.03483823,
        -0.07509449,  0.00362723, -0.06262924,  0.00247735,  0.        ,
        -0.03720904]])

In [79]:
model_all_logistic_L1 = LogisticRegression(penalty="l1", C=0.01)

In [80]:
model_all_logistic_L1.fit(X, y)

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [82]:
pred_logistic_l1 = model_all_logistic_L1.predict(X)

In [83]:
accuracy_score(y, pred_logistic_l1)

0.78722451173624797

In [84]:
model_all_logistic_L1.coef_

array([[ -7.98077588e-03,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   1.93838880e-04,
         -9.76628729e-01,  -2.74065234e-01,  -5.50912931e-01,
         -1.87371313e-02,  -2.35783252e-03,   4.69109012e-03,
         -1.27661086e-01,   7.26157658e-04,   7.15574124e-02,
         -1.73886179e-01]])